# Generated by Django 2.0.6 on 2018-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20180817_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_product',
            name='unit',
            field=models.CharField(max_length=30, null=True, verbose_name='单位'),
        ),
    ]
